### ISSUE TITLE
Order not created

### ISSUE THREAD

**Issue by katiasmet-93** [payloadcms/template-ecommerce-nextjs#2]
Hi,

Thank you for this great demo template! I tested it as a demo and there is no order created when I do a purchase.
Everything looks successful and there is no error, maybe this is still a small bug in the template. 

Would be nice if a demo shop is hosted somewhere just to check how an order looks like in Payload :).

**Comment by jacobsfletch** [comment]
Hey @katiasmet-93! It's very exciting to hear you've got it up and running. That issue has actually been fixed in the latest codebase. This repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/master/templates/ecommerce. If you're able to clone down a fresh template using the latest code, you'll see orders are created upon checkout as expected. I'm going to close this issue out now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload).

**Comment by jacobsfletch** [comment]
Oh and RE hosting a shop somewhere online, TOTALLY. This has been on my list of things to do for quite some time. I completely agree that this would be a very helpful resource to have. It'll get done at some point for sure 👍
